language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

env:
  - JYTHON=true
  - JYTHON=false

matrix:
  exclude:
    - python: "2.6"
      env: JYTHON=true
    - python: "2.7"
      env: JYTHON=true
    - python: "3.2"
      env: JYTHON=true
    - python: "3.3"
      env: JYTHON=true

before_install:
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.5.3/jython-installer-2.5.3.jar'
  - if [ "$JYTHON" == "true" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH; fi

before_script: if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi

script: $PYTHON_EXE setup.py nosetests --with-coverage --cover-package=xmltodict
